/**
 * Generate a random anonymous-style display name for posts (e.g. GuestFalcon27, CrimsonPulse91).
 * Used when user checks "Post anonymously" on the Post Your Take form.
 * Adjectives + nouns chosen for variety (animals, nature, abstract, colors, traits).
 *
 * Unique usernames = ADJECTIVES.length × NOUNS.length × 100 (suffix 00–99).
 * Current: 42 × 43 × 100 = 180,600. Consider expanding lists or adding suffix range when needed.
 */
const ADJECTIVES = [
  "Guest",
  "Blue",
  "Quiet",
  "Swift",
  "Bold",
  "Calm",
  "Silent",
  "Wise",
  "Bright",
  "Quick",
  "Cool",
  "Fair",
  "Lucky",
  "Brave",
  "Clear",
  "Stealth",
  "Crimson",
  "Lunar",
  "Solar",
  "Arctic",
  "Misty",
  "Golden",
  "Silver",
  "Shadow",
  "Frost",
  "Storm",
  "Wild",
  "Smooth",
  "Sharp",
  "Noble",
  "Rusty",
  "Cosmic",
  "Neon",
  "Velvet",
  "Iron",
  "Ghost",
  "Echo",
  "Pulse",
  "Flame",
  "Coral",
  "Jade",
  "Amber",
  "Onyx",
];
const NOUNS = [
  "Falcon",
  "Otter",
  "Trader",
  "Wolf",
  "Fox",
  "Bear",
  "Hawk",
  "Lynx",
  "Seal",
  "Crow",
  "Panda",
  "Tiger",
  "Eagle",
  "Raven",
  "Moth",
  "Vault",
  "Pulse",
  "Flux",
  "Drift",
  "Rider",
  "Strider",
  "Walker",
  "Sage",
  "Muse",
  "Forge",
  "Spark",
  "Blade",
  "Stone",
  "Bolt",
  "Wave",
  "Peak",
  "Dune",
  "Frost",
  "Ember",
  "Cipher",
  "Lens",
  "Prism",
  "Orbit",
  "Nova",
  "Apex",
  "Zenith",
  "Crest",
  "Shard",
  "Veil",
  "Rune",
  "Glyph",
  "Pine",
  "Elm",
  "Ivy",
  "Reed",
  "Fern",
  "Moss",
  "Briar",
  "Clover",
  "Haze",
];

export function generateAnonymousUsername(): string {
  const adj = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)];
  const num = Math.floor(Math.random() * 100);
  const suffix = num < 10 ? `0${num}` : String(num);
  return `${adj}${noun}${suffix}`;
}
